# Problem 29
# How many distint terms are in the sequence generated by a^b for
# 2<=a<=100 and 2<=b<=100?

def problem29(a, b):
	mmm = []
	for i in range(2, a+1):
		for j in range(2, b+1):
			mmm.append(i**j)
	return len(set(mmm))

if __name__ == '__main__':
	print problem29(5, 5)
	print problem29(100, 100)